'use strict';

const fs = require('fs');
const { decodeMap } = require('./binary-packer');
const { Grid } = require('./grid');
const { TILE } = require('./model');

/*
	Playability/connectivity report for an EXISTING Celeste .bin — vanilla,
	hand-authored, or generated by this tool. Read-only: decodes the map and
	inspects it, never rewrites anything.

	Two kinds of check:
	  - per room: is there a player spawn, and is the open (non-solid) space
	    one connected pocket reachable from it? (a sealed-off pit or an
	    isolated ledge shows up as unreachable air)
	  - per adjacent room pair: rooms whose world rectangles touch an edge but
	    have no aligned opening on that shared border are flagged — the layout
	    LOOKS connected but there is no way to actually walk between them.
*/

function findChild(node, name) {
	return (node.children || []).find((c) => c.name === name);
}
function findChildren(node, name) {
	return (node.children || []).filter((c) => c.name === name);
}

function parseGridInnerText(innerText, w, h) {
	const grid = new Grid(w, h, '0');
	const rows = (innerText || '').split('\n');
	for (let y = 0; y < h; y++) {
		const row = rows[y] || '';
		for (let x = 0; x < w; x++) grid.set(x, y, row[x] || '0');
	}
	return grid;
}

/** 4-connected flood fill over non-solid cells, starting from `starts`
    (room-local tile coords). Returns the count of reached cells and the
    total number of non-solid cells in the room. */
function floodFromCells(solids, w, h, starts) {
	const open = (x, y) => x >= 0 && y >= 0 && x < w && y < h && !solids.solid(x, y);
	let totalOpen = 0;
	for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) if (open(x, y)) totalOpen++;

	const seen = new Set();
	const q = [];
	for (const c of starts) {
		if (open(c.x, c.y)) {
			const k = c.y * w + c.x;
			if (!seen.has(k)) {
				seen.add(k);
				q.push([c.x, c.y]);
			}
		}
	}
	while (q.length) {
		const [x, y] = q.pop();
		for (const [dx, dy] of [
			[1, 0],
			[-1, 0],
			[0, 1],
			[0, -1],
		]) {
			const nx = x + dx;
			const ny = y + dy;
			if (!open(nx, ny)) continue;
			const k = ny * w + nx;
			if (seen.has(k)) continue;
			seen.add(k);
			q.push([nx, ny]);
		}
	}
	return { reached: seen.size, totalOpen };
}

/** Do two rooms' world-pixel rects touch along a shared edge, and if so,
    return the overlapping span (in world pixels) along that edge. */
function sharedBorder(a, b) {
	if (a.x + a.wPx === b.x || b.x + b.wPx === a.x) {
		const lo = Math.max(a.y, b.y);
		const hi = Math.min(a.y + a.hPx, b.y + b.hPx);
		if (hi > lo) return { axis: 'v', lo, hi, aIsLeft: a.x + a.wPx === b.x };
	}
	if (a.y + a.hPx === b.y || b.y + b.hPx === a.y) {
		const lo = Math.max(a.x, b.x);
		const hi = Math.min(a.x + a.wPx, b.x + b.wPx);
		if (hi > lo) return { axis: 'h', lo, hi, aIsAbove: a.y + a.hPx === b.y };
	}
	return null;
}

/** is there at least one non-solid cell on room `r`'s border facing the
    shared span [lo, hi) (world pixels), on the given side? */
function hasOpeningOnBorder(r, side, lo, hi) {
	const loTile = Math.floor((lo - (side === 'left' || side === 'right' ? r.y : r.x)) / TILE);
	const hiTile = Math.ceil((hi - (side === 'left' || side === 'right' ? r.y : r.x)) / TILE);
	if (side === 'left') {
		for (let y = loTile; y < hiTile; y++) if (!r.solids.solid(0, y)) return true;
	} else if (side === 'right') {
		for (let y = loTile; y < hiTile; y++) if (!r.solids.solid(r.wTiles - 1, y)) return true;
	} else if (side === 'top') {
		for (let x = loTile; x < hiTile; x++) if (!r.solids.solid(x, 0)) return true;
	} else if (side === 'bottom') {
		for (let x = loTile; x < hiTile; x++) if (!r.solids.solid(x, r.hTiles - 1)) return true;
	}
	return false;
}

function analyzeBin(binPath) {
	const buf = fs.readFileSync(binPath);
	const { root, package: pkg } = decodeMap(buf);
	const levelsNode = findChild(root, 'levels');
	const levelNodes = levelsNode ? findChildren(levelsNode, 'level') : [];
	if (!levelNodes.length) {
		throw new Error(`no <level> elements found in ${binPath} — is this a valid Celeste .bin?`);
	}

	const rooms = levelNodes.map((node, i) => {
		const attrs = node.attrs || {};
		const x = attrs.x || 0;
		const y = attrs.y || 0;
		const wPx = attrs.width || 0;
		const hPx = attrs.height || 0;
		const wTiles = Math.round(wPx / TILE);
		const hTiles = Math.round(hPx / TILE);

		const solidsNode = findChild(node, 'solids');
		const solids = parseGridInnerText(solidsNode && solidsNode.innerText, wTiles, hTiles);

		const entitiesNode = findChild(node, 'entities');
		const entityNodes = entitiesNode ? entitiesNode.children || [] : [];
		const entities = entityNodes.map((e) => ({
			name: e.name,
			gx: Math.round((((e.attrs && e.attrs.x) || 0) - x) / TILE),
			gy: Math.round((((e.attrs && e.attrs.y) || 0) - y) / TILE),
		}));
		const triggersNode = findChild(node, 'triggers');
		const triggerCount = triggersNode ? (triggersNode.children || []).length : 0;

		return {
			name: attrs.name || `level_${i}`,
			x,
			y,
			wPx,
			hPx,
			wTiles,
			hTiles,
			solids,
			entities,
			triggerCount,
			warnings: [],
		};
	});

	const entityCounts = {};
	for (const r of rooms) {
		let solidCount = 0;
		for (let yy = 0; yy < r.hTiles; yy++)
			for (let xx = 0; xx < r.wTiles; xx++) if (r.solids.solid(xx, yy)) solidCount++;
		const total = r.wTiles * r.hTiles;
		r.solidCount = solidCount;
		r.airCount = total - solidCount;
		r.density = total > 0 ? solidCount / total : 0;

		for (const e of r.entities) entityCounts[e.name] = (entityCounts[e.name] || 0) + 1;

		const spawns = r.entities.filter((e) => e.name === 'player');
		r.hasSpawn = spawns.length > 0;
		if (!r.hasSpawn) r.warnings.push('no player spawn in this room');

		if (r.airCount === 0) {
			r.warnings.push('room is entirely solid (no open space)');
			r.reachablePct = 0;
		} else {
			// Entity y is Celeste's ground-contact point (bottom of the hitbox),
			// which sits on the solid tile below the actual standing cell — flood
			// from one tile up, and fall back to the entity's own cell if that's
			// solid too (e.g. a flush ceiling).
			const starts = spawns.length
				? spawns.flatMap((e) => [
						{ x: e.gx, y: e.gy - 1 },
						{ x: e.gx, y: e.gy },
				  ])
				: (() => {
						// no spawn to flood from: fall back to the first open cell so we
						// can still report a connectivity number, but say so.
						for (let yy = 0; yy < r.hTiles; yy++)
							for (let xx = 0; xx < r.wTiles; xx++)
								if (!r.solids.solid(xx, yy)) return [{ x: xx, y: yy }];
						return [];
				  })();
			const { reached, totalOpen } = floodFromCells(r.solids, r.wTiles, r.hTiles, starts);
			r.reachablePct = totalOpen > 0 ? reached / totalOpen : 1;
			if (r.reachablePct < 0.95) {
				r.warnings.push(
					`only ${Math.round(r.reachablePct * 100)}% of open space reachable from spawn — likely a sealed pocket`,
				);
			}
		}
	}

	// cross-room adjacency: rects that touch but have no carved opening
	const sealedAdjacencies = [];
	for (let i = 0; i < rooms.length; i++) {
		for (let j = i + 1; j < rooms.length; j++) {
			const a = rooms[i];
			const b = rooms[j];
			const border = sharedBorder(
				{ x: a.x, y: a.y, wPx: a.wPx, hPx: a.hPx },
				{ x: b.x, y: b.y, wPx: b.wPx, hPx: b.hPx },
			);
			if (!border) continue;

			let openA, openB;
			if (border.axis === 'v') {
				openA = hasOpeningOnBorder(a, border.aIsLeft ? 'right' : 'left', border.lo, border.hi);
				openB = hasOpeningOnBorder(b, border.aIsLeft ? 'left' : 'right', border.lo, border.hi);
			} else {
				openA = hasOpeningOnBorder(a, border.aIsAbove ? 'bottom' : 'top', border.lo, border.hi);
				openB = hasOpeningOnBorder(b, border.aIsAbove ? 'top' : 'bottom', border.lo, border.hi);
			}
			if (!openA || !openB) {
				sealedAdjacencies.push({ a: a.name, b: b.name });
			}
		}
	}

	return {
		packageName: pkg,
		roomCount: rooms.length,
		entityCounts,
		sealedAdjacencies,
		rooms: rooms.map((r) => ({
			name: r.name,
			wTiles: r.wTiles,
			hTiles: r.hTiles,
			density: r.density,
			hasSpawn: r.hasSpawn,
			reachablePct: r.reachablePct,
			entityCount: r.entities.length,
			triggerCount: r.triggerCount,
			warnings: r.warnings,
		})),
	};
}

module.exports = { analyzeBin };
